sudo: required

services:
  - docker
language: node_js
node_js:
  - "6"
after_success:
 - "docker login -u $DOCKER_USER -p $DOCKER_PWD"
 - "docker build -t $DOCKER_USER/cloud-project ."
 - "docker push $DOCKER_USER/cloud-project"
