version: '2'
services:
  server:
    image: vladmourier/cloud-project
    links:
       - bd
    labels:
     - "traefik.port=80"
     - "traefik.backend=back"
     - "traefik.frontend.rule=Host:ec2-52-50-237-127.eu-west-1.compute.amazonaws.com"
     - "traefik.frontend.entryPoints=http"
  bd:
    image: redis
    labels:
      - "traefik.enable=false"
  traefik:
    image: traefik
    command: --web --docker --docker.domain=localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
- "traefik.enable=false"